version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: "v1.9"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
